Fixed a nasty bug in the interaction between BoundTraitProperties and @classorinstancemthod.
Turns out the descriptor logic was being called twice, which meant that there were lots of errors with two arguments instead of one:

E   TypeError: set_short_name() missing 1 required positional argument: 'value'

branch: ASVO-934-a